server:
  port: 8085
spring:
  application:
    name: review
  config:
    import: "optional:file:.env.review[.properties]"
  output:
    ansi:
      enabled: always

  jackson:
    serialization:
      fail-on-empty-beans: false

  datasource:
    url: jdbc:postgresql://localhost:5432/mossy
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 100

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: review

  cache:
    type: redis

# S3
cloud:
  aws:
    s3:
      bucket: ${CLOUD_AWS_S3_BUCKET}
    credentials:
      access-key: ${CLOUD_AWS_ACCESS_KEY}
      secret-key: ${CLOUD_AWS_SECRET_KEY}
    region: ${CLOUD_AWS_REGION}

# 모든 서비스에서 동일한 경로로 스웨거 사용
springdoc:
  swagger-ui:
    path: /mossy-docs
  api-docs:
    path: /v3/api-docs
