services:
  cash-service:
    build:
      context: ../src/backend
      dockerfile: cash-service/Dockerfile
    container_name: cash-service
    restart: always
    ports:
      - "8083:8080"
    env_file:
      - ../envs/.env.cash
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - mossy-network

  payout-service:
    build:
      context: ../src/backend
      dockerfile: payout-service/Dockerfile
    container_name: payout-service
    restart: always
    ports:
      - "8084:8080"
    env_file:
      - ../envs/.env.common
      - ../envs/.env.payout
    networks:
      - mossy-network

networks:
  mossy-network:
    external: true