include:
  - compose-kafka.yml
  - compose-redis.yml
  - elasticsearch/compose-es.yml
  - market/compose-market.yml
  - product/compose-product.yml
  - member/compose-member.yml
  - auth/compose-auth.yml
  - cash/compose-cash.yml
  - ai/compose-ai.yml
  - review/compose-review.yml
  - gateway/compose-gateway.yml

services:
  market:
    depends_on:
      redis:
        condition: service_healthy
      redpanda:
        condition: service_healthy
  product:
    depends_on:
      elasticsearch:
        condition: service_healthy
      redis:
        condition: service_healthy
      redpanda:
        condition: service_healthy
  member:
    depends_on:
      redis:
        condition: service_healthy
      redpanda:
        condition: service_healthy
  cash:
    depends_on:
      redis:
        condition: service_healthy
      redpanda:
        condition: service_healthy
  auth:
    depends_on:
      redis:
        condition: service_healthy
  review:
    depends_on:
      redpanda:
        condition: service_healthy
  ai:
    depends_on:
      redis:
        condition: service_healthy
      redpanda:
        condition: service_healthy
  gateway:
    depends_on:
      - market
      - product
      - member
      - auth
      - cash
      - review
      - ai


networks:
  mossy-network:
    name: mossy-network
    driver: bridge