services:
  # 유레카 서버 추가
  eureka-service:
    build:
      context: ..
      dockerfile: gateway/Dockerfile-eureka
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - mossy-network
  gateway:
    build:
      context: ..
      dockerfile: gateway/Dockerfile-gateway
    container_name: gateway-service
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - ./.env.gateway
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - eureka-service
    networks:
      - mossy-network

networks:
  mossy-network:
    external: true