services:
  auth:
    build:
      context: ..
      dockerfile: auth/Dockerfile
    container_name: auth
    restart: always
    ports:
      - "8086:8086"
    env_file:
      - .env.auth
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - mossy-network

networks:
  mossy-network:
    external: true