server:
  port: 8082
spring:
  application:
    name: member
  config:
    import: "optional:file:.env.member[.properties]"
  output:
    ansi:
      enabled: always
  jackson:
    serialization:
      fail-on-empty-beans: false
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    properties:
      hibernate:
        default_batch_fetch_size: 100
  sql:
    init:
      mode: always
      continue-on-error: true
  cache:
    type: redis
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: member
springdoc:
  swagger-ui:
    path: /mossy-docs
  api-docs:
    path: /v3/api-docs

# S3
cloud:
  aws:
    s3:
      bucket: ${CLOUD_AWS_S3_BUCKET}
    credentials:
      access-key: ${CLOUD_AWS_ACCESS_KEY}
      secret-key: ${CLOUD_AWS_SECRET_KEY}
    region: ${CLOUD_AWS_REGION}