server:
  port: 8080

spring:
  application:
    name: gateway

  config:
    import: "optional:file:.env.gateway[.properties]"

  cloud:
    gateway:
      routes:
        - id: market
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/cart/**, /api/v1/orders/**, /api/v1/payments/**, /api/v1/product/**
          filters:
            - name: JwtAuthenticationFilter

        - id: member-public
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/users/signup

        - id: member-private
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/users/me, /api/v1/users/profile
          filters:
            - name: JwtAuthenticationFilter

        - id: cash
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/cash/**
          filters:
            - name: JwtAuthenticationFilter

        - id: payout
          uri: http://localhost:8084
          predicates:
            - Path=/api/payout/**
          filters:
            - name: JwtAuthenticationFilter

        - id: review
          uri: http://localhost:8085
          predicates:
            - Path=/api/v1/review/**
          filters:
            - name: JwtAuthenticationFilter

        - id: auth
          uri: http://localhost:8086
          predicates:
            - Path=/api/v1/auth/**

eureka:
  client:
    enabled: false

jwt:
  secret: ${JWT_SECRET}