apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
  namespace: backend
spec:
  serviceName: elasticsearch
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      # ES 구동을 위한 Host OS의 vm.max_map_count 설정 우회
      initContainers:
        - name: increase-vm-max-map
          image: busybox
          command: ["sysctl", "-w", "vm.max_map_count=262144"]
          securityContext:
            privileged: true
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:8.10.4
          command: [ "/bin/sh", "-c" ]
          args:
            - |
              if ! bin/elasticsearch-plugin list | grep -q analysis-nori; then
                bin/elasticsearch-plugin install --batch analysis-nori
              fi
              /usr/local/bin/docker-entrypoint.sh elasticsearch
          env:
            - name: discovery.type
              value: "single-node"
            - name: xpack.security.enabled
              value: "false" # MSA 환경 통신 테스트 편의를 위해 보안 임시 해제
            - name: ES_JAVA_OPTS
              value: "-Xms512m -Xmx512m" # t3.large 환경에 맞춰 Heap 사이즈 고정
          ports:
            - containerPort: 9200
              name: rest
            - containerPort: 9300
              name: inter-node
          resources:
            requests:
              cpu: "200m"
              memory: "1Gi"
            limits:
              cpu: "1000m"
              memory: "1.5Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: backend
spec:
  selector:
    app: elasticsearch
  ports:
    - port: 9200
      targetPort: 9200