services:
  review-service:
    build:
      context: ..
      dockerfile: review/Dockerfile
    container_name: review
    restart: always
    ports:
      - "8085:8080"
    env_file:
      - .env.review
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - mossy-network

networks:
  mossy-network:
    external: true