server:
  port: 8081

spring:
  application:
    name: market-service
  config:
    import: "optional:file:./../../envs/.env.market[.properties]"
  output:
    ansi:
      enabled: always

  jackson:
    serialization:
      fail-on-empty-beans: false

  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 100

  data:
    redis:
      host: localhost
      port: 6379

  elasticsearch:
    uris:
      - http://localhost:9200

  cache:
    type: redis

# 모든 서비스에서 동일한 경로로 스웨거 사용
springdoc:
  swagger-ui:
    path: /mossy-docs
  api-docs:
    path: /v3/api-docs

# S3
cloud:
  aws:
    s3:
      bucket: ${CLOUD_AWS_S3_BUCKET}
    credentials:
      access-key: ${CLOUD_AWS_ACCESS_KEY}
      secret-key: ${CLOUD_AWS_SECRET_KEY}
    region: ${CLOUD_AWS_REGION}

logging:
  level:
    com.back: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.springframework.transaction.interceptor: TRACE

market:
  policy:
    cart:
      max_quantity: 100

toss:
  payments:
    base-url: https://api.tosspayments.com
    secret-key: ${TOSS_SECRET_KEY:test_sk_*******************}