services:
  ai:
    build:
      context: ..
      dockerfile: ai/Dockerfile
    container_name: ai
    restart: always
    ports:
      - "8087:8087"
    env_file:
      - .env.ai
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - REDIS_HOST=redis
      - MOSSY_FEIGN_PRODUCT_URL=http://product:8090
    networks:
      - mossy-network