services:
  product:
    build:
      context: ..
      dockerfile: product/Dockerfile
    container_name: product
    restart: always
    ports:
      - "8090:8090"
    env_file:
      - ../.env.default
      - .env.product
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - mossy-network
