services:
  member:
    build:
      context: ..
      dockerfile: member/Dockerfile
    container_name: member
    restart: always
    ports:
      - "8082:8082"
    env_file:
      - .env.member
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - mossy-network
