include:
  - ../compose-infra.yml
  - ../compose-kafka.yml

services:
  market:1"
  env_file:
    - .env.market
  environment:
    - SPRING_PROFILES_ACTIVE=prod
  depends_on:
    redis:
    build:
      context: ..
      dockerfile: market/Dockerfile
    container_name: market
    restart: always
    ports:
      - "8081:808
        condition: service_healthy
      redpanda:
        condition: service_healthy
    networks:
      - mossy-network

networks:
  mossy-network:
    external: true
