include:
  - ../compose-infra.yml
  - ../compose-kafka.yml
  - ../elasticsearch/compose-es.yml

services:
  market:
    build:
      context: ..
      dockerfile: market/Dockerfile
    container_name: market
    restart: always
    ports:
      - "8081:8080"
    env_file:
      - .env.market
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      elasticsearch:
        condition: service_healthy
      redis:
        condition: service_healthy
      redpanda:
        condition: service_healthy
    networks:
      - mossy-network

networks:
  mossy-network:
    name: mossy-network
    driver: bridge