services:
  market:
    build:
      context: ..
      dockerfile: market/Dockerfile
    container_name: market
    restart: always
    ports:
      - "8081:8081"
    env_file:
      - .env.market
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - REDIS_HOST=redis
      - MOSSY_FEIGN_PRODUCT_URL=http://product:8090
    networks:
      - mossy-network
