services:
  payout:
    build:
      context: ..
      dockerfile: payout/Dockerfile
    container_name: payout
    restart: always
    ports:
      - "8084:8084"
    env_file:
      - .env.payout
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - mossy-network
