services:
  payout:
    build:
      context: ..
      dockerfile: payout/Dockerfile
    container_name: payout
    restart: always
    ports:
      - "8084:8080"
    env_file:
      - .env.payout
    networks:
      - mossy-network

networks:
  mossy-network:
    driver: bridge