services:
  payout-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: payout
    restart: always
    ports:
      - "8084:8080"
    env_file:
      - ../envs/.env.common
      - ../envs/.env.payout
    networks:
      - mossy-network

networks:
  mossy-network:
    external: true