spring:
  config:
    activate:
      on-profile: prod

  datasource:
    # PostgreSQL에 맞게 URL과 드라이버 변경
    url: jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: false

  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379

  elasticsearch:
    uris:
      - http://elasticsearch:9200

cloud:
  aws:
    s3:
      bucket: ${CLOUD_AWS_S3_BUCKET}
    credentials:
      access-key: ${CLOUD_AWS_CREDENTIALS_ACCESS_KEY}
      secret-key: ${CLOUD_AWS_CREDENTIALS_SECRET_KEY}
    region:
      static: ${CLOUD_AWS_REGION}

toss:
  secret-key: ${TOSS_SECRET_KEY}

logging:
  level:
    root: INFO